=head1 IPv6 Purser 

=head2 IPv6 Address Assignment System for the Greek School Network 

The IPv6 Purser is a simple persistent IPv6 Prefix assignment and
administration tool to help handle IPv6 address assignments for
subscribers in broadband networks. 

=head2 DATABASE SCHEMA

Use these declarations for the tables that this module uses:

 CREATE TABLE `groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(40) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
 )

 CREATE TABLE `pools` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `first_prefix` varchar(255) NOT NULL DEFAULT '',
  `purpose` varchar(25) NOT NULL DEFAULT '',
  `active` int(1) NOT NULL DEFAULT '0',
  `length` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
 )

 CREATE TABLE `ipv6_static` (
  `group_id` int(10) unsigned NOT NULL,
  `username` varchar(255) COLLATE utf8_swedish_ci NOT NULL,
  `address` int(10) unsigned NOT NULL,
  `changetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createtime` datetime NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `in_use` tinyint(1) NOT NULL DEFAULT '1',
  UNIQUE KEY `s1` (`username`,`group_id`),
  UNIQUE KEY `s3` (`group_id`,`address`),
  KEY `s2` (`group_id`,`in_use`,`changetime`)
 ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci

 CREATE TABLE `ipv6_log` (
  `group_id` int(10) unsigned NOT NULL,
  `username` varchar(64) NOT NULL,
  `address` int(10) unsigned NOT NULL,
  `starttime` datetime NOT NULL,
  `stoptime` datetime NOT NULL,
  KEY `s1` (`group_id`,`username`),
  KEY `s2` (`starttime`,`stoptime`)
 )

=head2 LICENSE

At this point, not yet decided. To be continued. In the meantime, use
the module only for noble purposes.  

=head2 BUGS

Surely there are more than a few. To report, open an issue at github,
make a pull request, mail the author, do whatever strikes your fancy.
Anything is acceptable.  

=head2 DISCLAIMER

This module may cause whatever you plug it into to go critical. The
author is not  responsible for whatever bad happens as a result.

However, I get all the good karma if you actually find it useful! 

=head2 AUTHOR 

Athanasios Douitsis L<mailto:aduitsis@cpan.org>






